steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/bazos-341220/nejdej:latest',
        '--cache-from',
        'gcr.io/bazos-341220/nejdej:latest',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bazos-341220/nejdej:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'nejdej',
        '--image',
        'gcr.io/bazos-341220/nejdej:latest',
        '--region',
        'europe-west4',
      ]
images:
  - gcr.io/bazos-341220/nejdej/:latest
