version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5632:5432' # expose pg on port 5632 to not collide with pg from elswhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust\

  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: NextjsDockerfile
    env_file:
      - .env
    depends_on:
      - postgres
volumes:
  db_data:
