version: '2'
services:
  nejdej_db:
    image: mysql:latest
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
